name: Build-and-Upload-Openwrt-x86_64

on: 

  # push:
  #  branches: 
  #    - master
    paths:
      - 'openwrt/x86_64/.config'
      - '.github/workflows/B&U-Openwrt-original-x86_64.yml'
 # schedule:
      #  - cron: 0 */4 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Clean environment.
      env:
          DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d/*
        sudo swapoff /swapfile
        sudo rm -f /swapfile
        sudo -E apt-get -qq purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install mkisofs build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        curl -fsSL https://raw.githubusercontent.com/1orz/My-action/master/.bashrc >> ~/.bashrc
        sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

    - name: Clone source and install
      run: |
        git clone https://github.com/openwrt/openwrt
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Download and Load custom configuration
      run: |
        cd openwrt
        curl -fsSL https://raw.githubusercontent.com/1orz/My-action/master/openwrt/x86_64/.config >.config
        bash <(curl -fsSL https://raw.githubusercontent.com/1orz/My-action/master/openwrt/diy.sh)
        ./scripts/feeds install -a
        make defconfig

    - name: Download package
      run: |
        cd openwrt
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Multi-core compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        df -h
        make -j$(nproc)
        df -h

    - name: Single-core compile
      if: failure()
      run: |
        df -h
        cd openwrt
        make -j1 V=s
        df -h

    - name: Upload entire bin directory
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Openwrt-x86_64-bin-dictionary
        path: openwrt/bin

    - name: Setup Upload dictionary
      if: always()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "::set-env name=FIRMWARE::$(pwd)"

    - name: Only Upload firmware (Without packages)
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Openwrt-x86_64_firmware
        path: ${{ env.FIRMWARE }}
    
    - name: Upload firmware to Main Download Station (Without packages)
      if: success()
      run: |
        cd openwrt/bin/targets/*/*
        zip -r -o openwrt-original-x86_64.zip ./
        curl -F "token=${{ secrets.UPLOAD_TOKEN }}" -F "location=Router/Openwrt/x86_64/Original" -F "file=@openwrt-original-x86_64.zip" ${{ secrets.MAIN_UPLOAD_PROCESSOR }}
