name: ssh-to-action

on:
  # push:
  #   branches:
  #    - master
    paths:
      - '.github/workflows/Use-SSH.yml'    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15.2
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.2
      
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: SSH connection to Actions
        uses: 1orz/ssh-action@master

      - name: Upload Flies
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: Files
          path: upload/
